site_name: Mkdocs Bulma Classes Plugin
site_description: Add support to Bulma css framework in Mkdocs
site_url: https://daniele-tentoni.github.io/mkdocs-bulma-classes-plugin
site_author: Daniele Tentoni

repo_url: https://github.com/daniele-tentoni/mkdocs-bulma-classes-plugin
edit_uri: 'edit/main/docs'

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Markdown: markdown.md
  - Bulma:
      - Elements:
          - Tag: bulma/elements/tag.md
          - Title: bulma/elements/title.md
      - Helpers:
          - Typography: bulma/helpers/typography.md

theme:
    name: bulma

plugins:
    - bulma-classes
